context:
  version: "0.7.0"

package:
  name: crysfml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/crysfml/crysfml-${{ version }}.tar.gz
  sha256: 3a65bdd2b406aaeebcf7dcc82d6ed5c8d04dfaa6a4f1e0b69da9713469320d26

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: match(python, "<3.11")

requirements:
  build:
    - if: unix
      then:
        - make
        - ${{ stdlib("c") }}
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('fortran') }}
        - cmake
    - if: win
      then:
        - ninja
        - ${{ stdlib("m2w64_c") }}
        - ${{ compiler("m2w64_c") }}
        - ${{ compiler("m2w64_fortran") }}
        - cmake
    - if: build_platform != host_platform
      then:
        - python
        - cross-python_${{ host_platform }}
  host:
    - python
    - scikit-build-core >=0.11
    - versioningit
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - crysfml
      pip_check: true

about:
  summary: Python access to the CrysFML2008 crystallographic Fortran library
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
    - repo/CFML/LICENSE
  homepage: https://pypi.org/project/crysfml/

extra:
  recipe-maintainers:
    - MridulS
